spring:
  application:
    name: flashCoupon

  # JPA & Hibernate 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none                  # 실무/운영 기본값 (local에서는 update로 오버라이드)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # N+1 문제 방지를 위한 핵심 설정
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      add-mappings: false

server:
  servlet:
    context-path: /api/flashCoupon
  error:
    include-message: always

# 보안 설정
jwt:
  secret: "bXktc3VwZXItc2VjcmV0LWtleS1ieXRlcy0zMi1vci1tb3JlISE="
  access-token-minutes: 30
  refresh-token-days: 14
  issuer: flashCoupon

springdoc:
  swagger-ui:
    path: /docs