spring:
  application:
    name: timetracking
  web:
    resources:
      add-mappings: false

server:
  servlet:
    context-path: /api/timetracking
  error:
    include-message: always

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  access-token-minutes: 60
  issuer: timetracking

springdoc:
  swagger-ui:
    path: /docs
