spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8010

jwt:
  secret: "bXktc3VwZXItc2VjcmV0LWtleS1ieXRlcy0zMi1vci1tb3JlISE="

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
